### PR TITLE
Fix: contact form

### LINKED ISSUE #1821: Bloc FAQ contact
La mise en page du bloc n'est pas idéale en 320px.
- texte trop gros
- icône pas alignée

### LINKED ISSUE #1839: Contact form
**RGAA reference:** https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11

## Describe the problem

Le formulaire n'est n'apparaît que lors d'un choix locataire/propriétaire.

Les champs obligatoires sont représentés via une astérisque. Tous les champs du formulaire sont obligatoire.
La validation s'effectue au `blur` ce qui peut perturber le remplissage. Valider à la soumission est généralement conseillé.
Le format attendu dans le `placeholder` n'est pas retranscrit par un lecteur d'écran. 

## Expected behavior

Simplifier la consigne en déclarant "Tous les champs sont obligatoires" pour réduire la charge cognitive (devoir vérifier si le champ est obligatoire à chaque fois).
Crééer une liste des champs invalides à la validation au-dessus du formulaire.
Ajouter les exemples de formats attendu à côté des libellés.

## Screenshots

Image

### Desktop (please complete the following information):

 - OS: Fedora 43 (linux)
 - Browser: Chromium
 - Version: 143.0

### PR DESCRIPTION
**Pull request by narduin**
- Change form validation logic from component based to API (still with vee-validate).
- Create an example from another validation lib (more recent and flexible).
- Use a patched version of DsfrModal.
- Change accordions styles to fix mobile layout.

fixes #1839 
fixes #1821

### CODE REVIEW

**Comment by tristanrobert** [comment]
### :warning: **Snyk checks are incomplete.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :warning: | Open Source Security| 0 | 0 | 0 | 0 | [ See details ](https://app.snyk.io/org/mtes-mct/pr-checks/111e8675-f7c8-49f6-a5ee-6af4dfaaa8c8?refs=83feeed3b066d35b99d1e8478c9c7fcdd87dcd96&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by morganeboudin-cpu** [comment]
@narduin On peut basculer sur la version DSFR pour les accordéons

File: df-shared-next/src/components/form/FormWithValidation.vue [hunk 1]
```diff
@@ -0,0 +1,280 @@
...
+const onSuccess = (values: FormData) => {
+  // remove consent from sent values
+  const { consent, ...contactData } = values
+  emit('on-submit', contactData)
+}
+
+const onInvalidSubmit = async ({ errors }: InvalidSubmissionContext) => {
+  // focus the error summary if there are errors
+  if (errors) {
+    const errorSummaryTitle = errorSummary.value?.$el.querySelector('#error-summary-title')
```
Comment (narduin) [inline df-shared-next/src/components/form/FormWithValidation.vue]: déporter dans le composant error
