### PR TITLE
♿ fix: tenant-form

### LINKED ISSUE #1817: Bouton de suppression du nom d'usage conjoint
## Describe the problem

Dans le formulaire "Je renseigne les informations personnelles de mon conjoint”, le bouton pour supprimer le nom d’usage est de type `submit` par défaut.
Son action est déclenchée lors de la validation avec `entrée` au clavier.

Il lui faut un `type=button` pour éviter de supprimer la valeur du nom d'usage.

## To Reproduce

1. Créer un dossier
2. Ajouter un conjoint
3. Ajouter un nom d'usage au conjoint
4. Valider avec `entrée` dans n'importe quel champ
5. Le nom d'usage est supprimé

## Expected behavior

Le nom d'usage est conservé, le formulaire est sauvegardé.

### Desktop (please complete the following information):
 - OS: Fedora 43 (linux)
 - Browser: Chromium
 - Version: 143.0

### LINKED ISSUE #1829: Form tenant - input radios simulés
**RGAA reference:** https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/

## Describe the problem

Des choix entre "pour vous" / "pour un autre personne" sont stylisés comme des radios mais sont en fait des liens.
L'indicateur focus a été supprimé.
Les choix ont été groupés dans un élément `fieldset`, qui ne peut pas recevoir de `div`.

Étapes identifiées:
- identité - `/nom-locataire`
- Votre situation d'hébergement - `/documents-locataire`

## To Reproduce

1. Créer/éditer un dossier de location
2. Dans la page "identité"
3. Naviguer au clavier
4. Impossible de savoir quelle option est selectionnée

## Expected behavior

Créer une liste de liens.
Un indicateur de focus permet de sélectionner l'option.
Le style n'est pas trompeur.

### Desktop (please complete the following information):

 - OS: Fedora 43 (linux)
 - Browser: Chromium/Firefox
 - Version: 143.0

### LINKED ISSUE #1830: Form tenant - champs obligatoires
**RGAA reference:** https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.10

## Describe the problem

Les champs obligatoires ne sont pas identifiables explicitement (l'astérisque ne suffit pas).
Reco: écrire "obligatoire"/"facultatif". À défaut: expliquer la signification de l'astérisque.

## To Reproduce

1. Créer/éditer un dossier
2. valider une étape sans renseigner certains champs
3. erreur de champ requis

## Expected behavior

Les champs obligatoires doivent être identifiables lors de la saisie, si possible avec une explication en amont.
Ils doivent également contenir l'attribut `required` en html.

### Desktop (please complete the following information):

 - OS: Fedora 43 (linux)
 - Browser: Chromium
 - Version: 143.0

### LINKED ISSUE #1831: Form tenant - Libellés non associés à leur champ
**RGAA reference:** https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#11.1

## Describe the problem

Il reste des champs dont le `label` n'est pas associé à l'`input`.

## To Reproduce

1. Créer un dossier pour un couple/colocation
2. Cliquer sur le libellé "Nom" ou "Prénom" du conjoint OU "L’adresse email de votre conjoint·e (facultatif)"
3. Le champ n'est pas activé

## Expected behavior

Chaque champ doit être associé à un libellé.

### Desktop (please complete the following information):

 - OS: Fedora 43 (linux)
 - Browser: Chromium
 - Version: 143.0

### LINKED ISSUE #1832: Parcours tenant - focus dans modale
**RGAA reference:** https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/

## Describe the problem

Le focus n'est pas positionné/capturé (focus-trap) dans les modales du parcours.

## To Reproduce

1. Créer un dossier
2. Ouvrir une modale (aperçu document, avertissement de fichiers manquants)
3. Utiliser le clavier pour faire avancer le focus
4. Le focus n'est pas positionné au bon endroit
5. Le focus sort de la modale

## Expected behavior

À l'ouverture, le focus est positionné sur un élément pertinent.
À la tabulation, le focus est coincé dans la modale.

### Desktop (please complete the following information):

 - OS: Fedora 43 (linux)
 - Browser: Chromium
 - Version: 143.0

### LINKED ISSUE #1835: Parcours tenant - styles différents
Sur la page de validation du dossier, le titre utilise une couleur différente du reste du parcours:
Bleu clair `color--secondary` au lieu du noir utilisé tout au long du parcours `--text-title-grey`

Image

### PR DESCRIPTION
**Pull request by narduin**
- Fix accessibility issues on tenant parcours.
   - explicit required/optional on labels
   - add missing `required` attribute
   - error handling on submit rather than on blur
- Create a patched `DsfrModal` to make it work in the project and enhance its accessibility.
   - change open/close logic: `defineModel` for the state, `open` for the appearance
- Update dsfr dependencies (to make the modal work but no luck)
- Change options presented as fake radios to a list of links, restore focus indicator

[Preview URL](https://dossierfacile-front-staging-locataire-pr1852.osc-fr1.scalingo.io/nom-locataire)

closes #1817
closes #1829 
closes #1830 
closes #1831 
closes #1832 
closes #1835

### CODE REVIEW

File: tenantv3/src/components/CoupleInformation.vue
Comment (narduin) [inline tenantv3/src/components/CoupleInformation.vue]: pas de TextField ?

File: monorepo.code-workspace [hunk 1]
```diff
@@ -0,0 +1,51 @@
+{
+  "folders": [
```
Comment (alixdeschamps) [inline monorepo.code-workspace]: pourquoi tu commit ce fichier finalement?
